### ISSUE TITLE
Issue displaying text in Maintenance Mode

### ISSUE THREAD

**Issue by martygilbert** [eduridden/moodle-theme_essential#10]
See attached.

I've noticed this in a couple of other areas, but can't reproduce it at this time.

In Maintenance Mode, the text often goes behind the menu bar.

Great theme!
![maintenance](https://f.cloud.github.com/assets/616253/753541/f472dfaa-e56c-11e2-8639-292185986ae4.png)

**Comment by eduridden** [comment]
Now rectified after changes to layout
