### ISSUE TITLE
edit drop down menus

### ISSUE THREAD

**Issue by danbuntu** [eduridden/moodle-theme_essential#105]
Hi

we've upgraded to moodle 2.6 and latest version of the essential theme.
The feedback i'm getting form our users is that they really don't like the new 'edit' dropdown. They far prefer the line of icons and find this faster to use and more discover able.
Would it be possible to add some kind of toggle for this option?
We've also seen issues where the edit dropdown isn't lining up with the content - please see the attach sceenshot.
![moodle-edit-menus](https://f.cloud.github.com/assets/688626/1876678/4a1ba396-7916-11e3-837f-da7e6707e26b.png)

**Comment by eduridden** [comment]
The theme is not doing this. The edit drop down is the new way 2.6 displays the edit buttons. As such there is nothing I can do from the theme. 

Julian

**Comment by danbuntu** [comment]
oh blast I hadn't realized that.
I'll have a look on the tracker then and see what I can find.
