### ISSUE TITLE
Blocks drag/drop does not seem to work properly on My Home page

### ISSUE THREAD

**Issue by euven** [eduridden/moodle-theme_essential#114]
Cannot move blocks to the main region on the left. Blocks can be moved out of this region, but not back

**Comment by lazydaisy** [comment]
This is a problem with Moodle and nothing to do with Essential theme. We are trying to fix this. Sorry for the inconvenience.

**Comment by euven** [comment]
Hi Mary,

Thanks for letting me know. Could you update here when the issue has been resolved?

Cheers,
Eugene.

**Comment by lazydaisy** [comment]
Best way is login to the Moodle Tracker and watch the progress by adding yourself in that tracker issue.
https://tracker.moodle.org/browse/MDL-41551

**Comment by gjb2048** [comment]
Can anybody close this?
