### ISSUE TITLE
page-header's full site name 

### ISSUE THREAD

**Issue by saeed3234** [eduridden/moodle-theme_essential#118]
There is a slight mistake in header.php in includes folder. 

"<h1 id="title"><?php echo $SITE->shortname; ?></h1>"

should be changed to

"<h1 id="title"><?php echo $SITE->fullname; ?></h1>"

Best
Saeed

PS: Sorry for the big font. I did not know how to insert the code to be displayed correctly.

**Comment by lazydaisy** [comment]
I don't think this is an error as such it is just unfortunate if you want to use the 'short name' as a Home link as described in the themes forum <a href="https://moodle.org/mod/forum/discuss.php?d=254833">HERE</a>

**Comment by gjb2048** [comment]
Close this?
