### ISSUE TITLE
Frontpage Slideshow

### ISSUE THREAD

**Issue by timboland15** [eduridden/moodle-theme_essential#12]
The first slide doesn't show correctly until after slides 2,3 & 4 have been shown and it wraps back round.

**Comment by jgcracknell** [comment]
Which browser?

**Comment by eduridden** [comment]
Sadly tis is above my ability to fix. i can say this is confirmed across all browsers. If anyone finds a fix and would like to push an answer to this repo I would be very appreciative.

Julian

**Comment by seasharp** [comment]
To resolve this issue go to frontpage.php and find where the HTML for each individual slide is created and remove the CSS class 'da-slide-toleft' from the containing div for each slide.  This class is not needed at initialization and will be properly added by the js file after initialization.  Once you remove this CSS class the slideshow will properly begin with slide 1.

**Comment by mcolliver** [comment]
The correction from @seasharp fixed this bug for me :+1: Thanks

**Comment by jgcracknell** [comment]
Has anyone got a patch/pull so I can test and not have to reinvent the wheel? :-)

**Comment by mcolliver** [comment]
I've forked the code and updated the frontpage.php code so that it works.
(not many changed so you could do manually - just search frontpage.php for da-slide-toleft)

If you want to see my fork is at
https://github.com/mcolliver/moodle-theme_essential

**Comment by eduridden** [comment]
Can I just say that @seasharp is a LEGEND! Bug fixed and patched in Master. Will make this fix as part of the next release (due very shortly)
