### ISSUE TITLE
FontAwesome CSS file is not available (not sent from the web server to the browser)

### ISSUE THREAD

**Issue by nadavkav** [eduridden/moodle-theme_essential#125]
On a fresh Moodle 2.7 install, For some strange reason, on our CenOS 6.2 server the file 
/theme/essential/style/font-awesome.min.css was not sent to the user's browser.

We Changed it to: /theme/essential/style/font-awesome-min.css
( ".min" to "-min" ) and also on the /theme/essential/config.php
And not it works :smile:

**Comment by DBezemer** [comment]
Fixing in my latest version at moodle.org

**Comment by DBezemer** [comment]
Fixed in latest releases and onwards

**Comment by nadavkav** [comment]
Sweeeeet :smile:
