### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by emanuelis** [eduridden/moodle-theme_essential#140]
Hi,
update from 2014020300 to 2014111002 fails on Moodle 2.8.1 :(
![b](https://cloud.githubusercontent.com/assets/329596/5114690/bb5a2c74-7043-11e4-9f6d-9371a62500ea.png)

**Comment by emanuelis** [comment]
Sorry, my mistake.

**Comment by scara** [comment]
FYI you should open/comment issues in https://github.com/gjb2048/moodle-theme_essential/issues: the developers team of this awesome theme has changed some time ago.
Refs.:
- http://gjb2048.github.io/moodle-theme_essential/
- https://moodle.org/plugins/view.php?plugin=theme_essential
- http://moodleman.net/articles/long-thanks-fish/
- https://moodle.org/mod/forum/discuss.php?d=272237
- https://moodle.org/mod/forum/discuss.php?d=264952
