### ISSUE TITLE
Invalid Error message and display difference (missing slideshow) when using IE10 64bit

### ISSUE THREAD

**Issue by jgcracknell** [eduridden/moodle-theme_essential#15]
When using IE10 on a 64bit machine I get the following error message and the slideshow doesn't display.

64 bit screenshot

![image](https://f.cloud.github.com/assets/1026079/819712/f0996620-efb6-11e2-9c42-d63c36d17470.png)

On a 32 bit IE it is fine - the slideshow is present and minus the comment about the upgrade being necessary.

**Comment by jgcracknell** [comment]
To add it is doing this with 32bit browsers in IE now.  Has something changed?

**Comment by jgcracknell** [comment]
This is all because of running IIS behind a reverse proxy.  The script asking for the user agent doesn't work in this case.  It works for other scripts.  So either the script needs to be altered or perhaps a method of being able to turn off the check would help.

**Comment by eduridden** [comment]
Sadly I am not an IIS admin and whould have no idea why the call would not work through a reverse proxy. This is a standard WC3 compliant call. I do not know another way of writing it. I also cannot drop it as it is an important request to make. Sadly I don't think I will have an answer for Reverse proxy use.
