### ISSUE TITLE
Can not upload Logo or slider images

### ISSUE THREAD

**Issue by jgcracknell** [eduridden/moodle-theme_essential#17]
In IE10 and Chrome can not upload slider images on latest release 2.5.2 and master

![image](https://f.cloud.github.com/assets/1026079/814221/86fa996e-ef11-11e2-8067-8eacc224f6f3.png)

I have reported it on Moodle tracker too because it seems to be every input on the latest 2.5 pull such as Afterburner logo too that is affected.

**Comment by eduridden** [comment]
I am closing this as it is not related to this theme. If you are having this in other places

Just FYI, running Moodle 2.4 or 2.5 I cannot replicate your issue in the brewers you mentioned. This would make it something isolated to your site and not a moodle bug.
