### ISSUE TITLE
Version 2013071700 unable to add blocks to front page FF 22 Mountain Lion

### ISSUE THREAD

**Issue by bobpuffer** [eduridden/moodle-theme_essential#18]
Theme caches (EVERY SINGLE cache) cleared.  Theme designer mode.

**Comment by bobpuffer** [comment]
Having gone into My home and come back out I can now add blocks.  What cache didn't get cleared?  Purged all.  Cleared theme caches.  Cleared FF's cache.

**Comment by eduridden** [comment]
I think this is tied to your other issue. I too am a mac man. This theme was built and tested on a Mac.

Can you grab the 2.5.2.1 update and try again please.
