### ISSUE TITLE
Unable to access ANY site administrative functions (nothing opens) version 2013071700

### ISSUE THREAD

**Issue by bobpuffer** [eduridden/moodle-theme_essential#19]
Version 2013071700
Theme caches (EVERY SINGLE cache) cleared even CSS Cachebuster.
Theme designer mode.
FF 22 OS X Mountain Lion

**Comment by bobpuffer** [comment]
Having gone into My Home and come back out to Home I can now access administrative functions, wonky.

**Comment by eduridden** [comment]
I don't believe this is a theme issue. I cannot replicate on my test sites. The fact it even repaired itself on yours thinks that maybe it was a bad locally cached version
