### ISSUE TITLE
Remove block title underline when block collapsed

### ISSUE THREAD

**Issue by ds125v** [eduridden/moodle-theme_essential#21]
It's a tiny little thing but there's a border-bottom on the title within a block. This looks a bit out of place when the block is collapsed so it might be better to remove this when the block is "hidden" (that's the class name but it's more like collapsed) or to add it to the top of the .block .content instead as that is the part that gets display none when the block is collapsed.

**Comment by ds125v** [comment]
If you do this you probably want to remove the margin bottom on the H2 as well when the block collapses. It's required for the spacing between the header and the line, but makes the collapsed block with no line look unbalanced.

**Comment by eduridden** [comment]
I too have a "visual" eye and the moment you mentioned this it has annoyed me ever since. I have added a commit to the MASTER branch that will do as you have described. Will roll it out in the next release.
