### ISSUE TITLE
Front page notice

### ISSUE THREAD

**Issue by bobpuffer** [eduridden/moodle-theme_essential#23]
Notice: Undefined variable: regionbsid in /opt/local/apache2/htdocs/moodle/theme/essential/layout/frontpage.php on line 352 Call Stack #TimeMemoryFunctionLocation 10.0024806232{main}( )../index.php:0 20.294340349920core_renderer->header( )../index.php:101 30.334741391568core_renderer->render_page_layout( ??? )../outputrenderers.php:777 40.335441604984include( '/opt/local/apache2/htdocs/moodle/theme/essential/layout/frontpage.php' )../outputrenderers.php:847 " class="span12"

**Comment by eduridden** [comment]
This is rectified in current build. Please grab latest copy.
