### ISSUE TITLE
All blocks added to front page go into Admin-only section/ cannot move blocks out of admin-only section into front page viewable area

### ISSUE THREAD

**Issue by bobpuffer** [eduridden/moodle-theme_essential#26]
I only have NAV in viewable area
Essential 2013071800
Moodle 20130712
Mountain Lion
FF 22 and Chrome 27
all caches cleared

**Comment by eduridden** [comment]
I believe this is now fixed in the master branch. Please test and let me know

**Comment by bobpuffer** [comment]
I can confirm, thanks.
