### ISSUE TITLE
Marketing spots will not take uploads of pics only urls

### ISSUE THREAD

**Issue by bobpuffer** [eduridden/moodle-theme_essential#27]

**Comment by eduridden** [comment]
This is not a theme bug or anything that can be fixed through the theme. Moodle does not allow the ability to add images in the HTML editor when used in themes. Closing as there is no bug to fix i the theme here,

**Comment by bobpuffer** [comment]
Probably something about what you've said I just don't get -- why are you able to upload images to be used as logo or into the footer section of the themes?

**Comment by eduridden** [comment]
Image used in the log is not using the HTML editor but a custom field added
in 2.5 that allows for file upload. The HTML editor is not capable of
uploading images in themes and this is an issue in Moodle in general and
happens across all themes. It is not something I can fix in this theme
