### ISSUE TITLE
Storange navbar separator color 

### ISSUE THREAD

**Issue by papillon326** [eduridden/moodle-theme_essential#28]
When Changing the theme Color I notice strange separator right of login info in navigation bar.
I think better to add this into CSS.

.navbar .pull-right.nav {
  border-color: <<Theme Color>>;
}

**Comment by eduridden** [comment]
I am closing this as I cannot replicate it on any sites. However if you can point me to a site where I can see this happening I am happy to re-open.

P.S. Are you sure you have the latest code?

Julian
