### ISSUE TITLE
Header on Chromium Browser

### ISSUE THREAD

**Issue by saadsm** [eduridden/moodle-theme_essential#30]
Hi, on the Chromium Browser, the icon seems to get mixed up with the text. I am sure its a small error as you havent tested on Chromium Browser,

heres the screenshot:

![screenshot-1](https://f.cloud.github.com/assets/1969307/855313/d49ad1ca-f51f-11e2-92ee-891f4194fdc8.png)

**Comment by eduridden** [comment]
I won't be testing for Chromium as it is used by such a minority of users. The theme however is being tested and updated for Chrome, Firefox, Safari and IE.

Julian

**Comment by saadsm** [comment]
Well, it was just one piece of line. Anyways. Cheers.
