### ISSUE TITLE
Drag and drop out of 'admin only' area 

### ISSUE THREAD

**Issue by ghost** [eduridden/moodle-theme_essential#32]
Great theme! I originally downloaded from Moodle repo, and then pulled most recent from this git repo.

After moving a block into the Admin Only section it is not possible to move it out. I cannot move it back up onto the page. I have tried editing the settings 

I did notice that the blocks that were originally on the front page had the up/down arrows instead of the drag/drop cross-hair.

I tried disabling/enabling AJAX, but this has not had any affect. It appears that blocks will only drag and drop between the 'admin only' section and the footer section. It is not possible to drag them back up onto the page.

I don't know if it is related, but I uploaded a logo image and now I cannot delete it. Every time I save after deleting it it reappears.

**Comment by eduridden** [comment]
This is now fixed in the 2.5.4 release.

**Comment by ghost** [comment]
Thank you!
