### ISSUE TITLE
FEATURE REQUEST: Please add Advark type messages

### ISSUE THREAD

**Issue by jgcracknell** [eduridden/moodle-theme_essential#42]
Hi Julian

Would it be possible to add the same sort of thing as found in Aardvark for snow days and other emergencies.  Would be good for onsite Internet issues that we sometimes have and Moodle being hosted on our internal server is best positioned to have such a message on it.

thanks

James

**Comment by eduridden** [comment]
I loved the idea and already have Shaun's blessing to use the same idea in Essential. I hope to have this ready for the next release
