### ISSUE TITLE
FEATURE REQUEST: Please add in Mail icons etc under Social Networking

### ISSUE THREAD

**Issue by jgcracknell** [eduridden/moodle-theme_essential#44]
Hi

Is it possible to add in appropriate icons for Mail, Calendar, Drive - particularly for say Google or MSOffice360 resources which many schools/institutions use.  Being able to put our own icons there as well for other resources like libraries would be useful too.

Thanks

**Comment by eduridden** [comment]
Than you for the suggestions. I will keep this in mind for future releases.
