### ISSUE TITLE
Navigation icons

### ISSUE THREAD

**Issue by isetz** [eduridden/moodle-theme_essential#55]
Hi, I was trying to modify the custom renderers of essential theme to add support for several icons that are not mapped there and I've found out that there is an issue in the course list navigation that loads using an Ajax call. When subitems are loaded using Ajax, the renderer is not called and then it loads the image icons from Moodle instead and not the Fontawesome ones.

Any thoughts? Maybe this is an issue that should be opened in moodle project?

**Comment by isetz** [comment]
Well I used CSS to solve the problem. Hiding the images and adding content before the link instead of using the renderer. But still I think there's an issue there. Thanks!

**Comment by eduridden** [comment]
I am closing this as it is not an Essential Bug. And yes.....needs to be urgently raised as a moodle bug. So many icons in moodle either have no class applied at all or have the same class used on several different icons. Is driving me crazy!
