### ISSUE TITLE
Issue when using HTTPS for login page

### ISSUE THREAD

**Issue by mcolliver** [eduridden/moodle-theme_essential#57]
If you set Moodle to force HTTPS for login page some of the page passed back by the theme does not convert to HTTPS protocol.

Particularly the call to Google fonts (as is a directly coded url http request in general.php and frontpage.php).

Can just change the Google fonts to be called using https (don't think this adds a problem - but think there is a clever way using a moodle function from memory).

Not sure about the awesome font calls in the CSS file as this might get cached... need to play around a bit more just to find out - think by using $CFG-->wwwroot it switched to https... but doesn't seem to for me at the moment.....

**Comment by mikebuchanon** [comment]
You could also just change http://fonts.googleapis.com to //fonts.googleapis.com.  That way they'll load according to how the page was served :)

**Comment by mcolliver** [comment]
Thanks - have also played around with lib.php so that font awesome and the body background image load using HTTPS when required to.

**Comment by eduridden** [comment]
I have implemented this fix into master. Also updated the lib.php as suggested
