### ISSUE TITLE
Cannot upgrade Essential theme when Essential theme is in use

### ISSUE THREAD

**Issue by vaughany** [eduridden/moodle-theme_essential#7]
Had an odd situation earlier. I did a pull on the git repo, then went to Moodle -> Notifications which said I had one plugin which needs upgrading, the Essential theme. When I went to click on the 'perform upgrade now' button, it was unclickable.

Changing to the Standard theme I was able to click the upgrade button, and with the Essential theme I was able to tab to the button and then hit space to activate it, but I could not click it with the mouse.

Looking at the HTML, I can see the following:

``` html
<div id="yui_3_9_1_3_1369209924955_20" class="span0">
    <div id="move" class="span12"> </div>
    <div class="span12" id="yui_3_9_1_3_1369209924955_21"> </div>
</div>
```

The span12's are contained within a span0, which may explain their visibility and tabbable / unclickable nature. I'll look into this more as time allows.

**Comment by vaughany** [comment]
After a little extra testing, this applies to installing/upgrading any plugin at all, not just this theme, but does appear to be caused by this theme.

**Comment by eduridden** [comment]
Rectified in the latest release
