### ISSUE TITLE
Cannot remove logo image

### ISSUE THREAD

**Issue by ghost** [eduridden/moodle-theme_essential#72]
Hi!

I am running the most recent version of this theme (2.5.4). I uploaded a logo image and now would like to remove it in favor of the Awesome font logos. The steps I have taken:
1. Open General Settings
2. click on the logo image (a .png)
3. Click the delete button
4. Click save changes
   The image persists.

I have tried clearing cache. This seems to have no effect.

How can I delete this image?

Thank you!

**Comment by ghost** [comment]
I think this is related to the above. It appears that it is not possible to remove images from the front page slideshow. I deleted each of three slides all of which had images. After clicking delete on each one, it appears that the images are gone. After leaving the page and coming back, the images are still there. As an aside, the slideshow does not appear to run unless there is a title present for an item - which is a good thing because it would be not good to have images running by themselves.

**Comment by eduridden** [comment]
Fixed in Essential 2.6.1 release
