### ISSUE TITLE
Restrict editing of footer blocks to site administrators only?

### ISSUE THREAD

**Issue by mattrice** [eduridden/moodle-theme_essential#74]
Is there a way to restrict editing the blocks in the footer (but still allow, e.g., instructors to edit block in their courses)?

I assume this can be solved with permissions, but I am unsure of where to look.

Thank you for your assistance!

**Comment by eduridden** [comment]
Yes this can be solved with permissions. Click on the edit icon of the block in question and then in the administration block you can see permissions. Here you can do some overrides. Please see the Moodledocs for more info. http://docs.moodle.org/25/en/Override_permissions
