### ISSUE TITLE
Using jquery in html block throws error in custom_1.0_min.js

### ISSUE THREAD

**Issue by mikebuchanon** [eduridden/moodle-theme_essential#75]
We created a simple HTML block that uses jQuery to load in some 'leaderboard' data from one of our other applications.  With the most recent version of the essential theme, this caused a JavaScript error on the console and the HTML block didn't load properly.  

The error:
TypeError: $ is not a function on line 1 in custom_1.0_min.js

I found an interesting StackOverflow write-up on this issue at http://stackoverflow.com/questions/12343714/typeerror-is-not-a-function-when-calling-jquery-function

I was able to get it to work by changing this file from:

``` JavaScript
(function(){$("h2.pagetitle span").html(function(i,text){return text.replace(/[a-zàâîïôèéêëèùûü]+/i,function(match){return'<span class="firstword">'+match+'</span>';});});$('#da-slider').cslider({autoplay:true,interval:6000});});
```

to:

``` JavaScript
jQuery(function($){$("h2.pagetitle span").html(function(i,text){return text.replace(/[a-zàâîïôèéêëèùûü]+/i,function(match){return'<span class="firstword">'+match+'</span>';});});$('#da-slider').cslider({autoplay:true,interval:6000});});
```

Just wanted to pass this along in case anyone else ran into a similar issue. Have a great day!
/mtb

**Comment by DBezemer** [comment]
mike, this is not the right way to fix it in my opinion.
jQuery simply always should be loaded in the correct version order to prevent these errors.

Newest version loaded first, older version loaded after. Additionally use noConflict() for conflicting code.

**Comment by mikebuchanon** [comment]
Sure, and we have noConflict() as part of our code to pull in the "leader board", but, it was still throwing an issue with this custom JavaScript.  Making the change I listed above resolved the issue for me and allowed the carousel to continue to function on the main site page :)

**Comment by eduridden** [comment]
I am with David. I am not keen to implement your solution for the reasons mentioned.

Feel free to change the local version you have however as you see fit. 

Julian
