### ISSUE TITLE
Possible double loading of bootstrap javascript files

### ISSUE THREAD

**Issue by mikebuchanon** [eduridden/moodle-theme_essential#76]
After the addition of the bootstrap.min.js file to the theme on Sept 23, it appears that we have two copies of the bootstrap javascript being loaded.  One by the base bootstrap theme and one by the essential theme.  

I noticed this because clicks on 'my dashboard' and 'my courses' stopped opening the dropdown menus on the first click.  A click on either of these two menu items and then a click elsewhere would cause the dropdown to open.

For an example of what I saw, see http://screencast.com/t/PV4cjpgxesc

By renaming bootstrap.min.js to bootstrap.min.js.bak and purging my Moodle caches, I was able to get the dropdowns to fire on one click as they had prior to this most recent update.  

Do we need bootstrap.min.js in the the theme if it's being loaded in the base theme?  Thanks for your help and your continued efforts!  We really love the theme! Let me know if I can ever help test anything. Cheers!
/mtb

**Comment by eduridden** [comment]
This is fixed in the current release. Thank you for the report
