### ISSUE TITLE
Support new Google analytics

### ISSUE THREAD

**Issue by DBezemer** [eduridden/moodle-theme_essential#79]
I have updated my own version of the analytics.php to support the new Google analytics code (Oct 2013) would you be interested in the source code?

Also, placement of the analytics code in the footer will prevent Google Analytics from working correctly, the embedding had to happen in the page header

If you would like the copy, I can either send it to you, or create a clone of this repo so I can create a pull request. Just indicate your preference :)

**Comment by eduridden** [comment]
would love a copy. Either method of fine and I can test then build it into the next release.

Julian

**Comment by DBezemer** [comment]
merge request sent

**Comment by eduridden** [comment]
And now pulled. Thanks for sending that through.
