### ISSUE TITLE
iOS7 on iPhone - Top most navigation labels disappear

### ISSUE THREAD

**Issue by howster** [eduridden/moodle-theme_essential#81]
Hi,
see attached iPhone screen shot using iOS7
![ios7 screenshot](https://f.cloud.github.com/assets/1191091/1351238/eaf9456e-371e-11e3-95cb-cfed81742f6a.jpg)
When you drag the screen to a small size on my pc/desktop the labels remain, Strange issue. Just iPhone problem.
Thanks

**Comment by howster** [comment]
desktop browser dragged to small screen size
![desktop](https://f.cloud.github.com/assets/1191091/1351248/36af2eb0-371f-11e3-9cbb-7e26d256283b.PNG)

**Comment by howster** [comment]
hmmm adding .nav-collapse{border: 1px solid #30ADD1;} to ...moodle/theme/essential/style/custom.css fixes it. Just enable Theme designer mode under Theme Settings to see change reflected

**Comment by eduridden** [comment]
Fixed and added to current stable release
