### ISSUE TITLE
Third level navigation items not displaying correctly

### ISSUE THREAD

**Issue by optimumtact** [eduridden/moodle-theme_essential#84]
Hi all
We've encountered an issue with navigation items that are 3 levels deep. As you can see from the attached screen shots they don't appear to pop out a new panel, they just extend the size of the 2nd level panel.

For now I've advised my clients to simply avoid 3rd level items, but I was wondering if this was a bug or the theme simply doesn't support that level of nesting.

The browser I used for testing was Firefox 25.0 for Ubuntu

![test](https://f.cloud.github.com/assets/2544323/1559293/2c6c7ac2-4fc8-11e3-9244-8bf67b2f1bc6.png)

![themebug](https://f.cloud.github.com/assets/2544323/1559294/2c6e54aa-4fc8-11e3-96bc-3a6eaab9a625.png)

Regards

**Comment by optimumtact** [comment]
I should say that we are using the 2.6 release of the theme.

**Comment by eduridden** [comment]
Sadly you will find the same issues in the core "clean" theme that this inherits from. Until they fix this bug in core there is not much I can do.

**Comment by optimumtact** [comment]
Righto. Thanks!
