### ISSUE TITLE
Update bootstrap to version 3

### ISSUE THREAD

**Issue by fabricioflores** [eduridden/moodle-theme_essential#95]
This isn't a really issue. I want to use some things from bootstrap 3 (like a better login form) and i want to know what i must change, and if i can help you to update bootstrap to this awsome theme

**Comment by eduridden** [comment]
I am playing with a new theme to use Bootstrap three styling. If successful I will also look at porting Essential. Really I want to wait for Moodle to upgrade its core code first.

**Comment by fabricioflores** [comment]
@moodleman great! if you want some help i want to do!

**Comment by gjb2048** [comment]
Now here: https://github.com/DBezemer/moodle-theme_essential/issues/24
